version: '3.9'
services:
  caddy_reverse_proxy:
    # Use the caddy:latest image from Docker Hub
    image: caddy:latest
    # Restart policy: restart the container unless explicitly stopped
    restart: unless-stopped
    container_name: caddy_proxy
    # ports for Caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      # Mount the host Caddyfile
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
    # Connect the Caddy container caddy_net
    networks:
      - caddy_net
    
  portainer:
    image: portainer/portainer-ee:latest
    restart: always
    # Map port 9000
    ports:
      - "9000:9000"
    # Add host directories to the container and persist Portainer data
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    # Add Portainer to the caddy_net network  
    networks:
     - caddy_net

volumes:
  caddy_data:
  portainer_data:
  caddy_config:
networks:
  caddy_net:
